# Generated by Django 3.2.3 on 2021-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookieslist',
            name='cookies',
            field=models.JSONField(null=True),
        ),
    ]
