# Generated by Django 3.2.3 on 2021-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_alter_cookieslist_cookies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField()),
                ('expirationDate', models.CharField(max_length=128, null=True)),
                ('hostOnly', models.BooleanField()),
                ('httpOnly', models.BooleanField()),
                ('name', models.CharField(max_length=128, null=True)),
                ('path', models.CharField(max_length=128, null=True)),
                ('sameSite', models.CharField(max_length=128, null=True)),
                ('secure', models.BooleanField()),
                ('session', models.BooleanField()),
                ('storeId', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=4096, null=True)),
            ],
        ),
    ]
