# Generated by Django 3.2.3 on 2021-11-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0004_alter_cookie_hostonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='httpOnly',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='secure',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='session',
            field=models.BooleanField(null=True),
        ),
    ]
